services:
  postgres:
    image: postgres:latest
    container_name: db_inst_api
    environment:
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: inst_api 
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    restart: always 

volumes:
  postgres-data:
    driver: local